language: ruby

script:
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake

rvm:
  - 2.3.1
notifications:
  email:
    recipients:
      - livreluan@gmail.com

branches:
  only:
    - devel

addons:
    code_climate:
            repo_token: 5891b1f77d783db65a29ab9ded1afd855b25cb15c9b4716f3b8f14757b7ed8a4
